x, y = 5.0, 10
print('x=', x , ',', 'y=', y)
import math
pi = math.pi
e = math.e
print('pi = ', pi)
print('rounded value of pi = ', round(pi,4))
pos_inf = float('inf')
neg_inf = float('-inf')
not_a_num = float('nan')
print('math.isinf(pos_inf) = ', math.isinf(pos_inf))
print('math.isinf(neg_inf) = ', math.isinf(neg_inf))
print('math.isnan(not_a_num) = ', math.isinf(not_a_num))
print('pos_inf * x = ', pos_inf * x)
print('neg_inf * x = ', neg_inf * x)
print('not_a_num * x = ', not_a_num * x)
print('pos_inf * x = ', pos_inf * x)
print('neg_inf / y = ', neg_inf / y)
print('not_a_num - y = ', not_a_num - y)
print('not_a_num == not_a_num = ', not_a_num == not_a_num)
print('math.factorial(5) =', math.factorial(5))
print('math.log(x) =', math.log(x))
print('math.log10(x) =', math.log10(x))
print('math.exp(x) =', math.exp(x))
print('math.pow(x, x) =', math.pow(x, x))
print('math.sqrt(25) =', math.sqrt(25))
print('match.cos(x) =', math.cos(x))
print('match.acos(0.284) =', math.acos(0.284))
print('match.degrees(x) =', math.degrees(x))
print('match.radians(286.5) =', math.radians(286.5))
print('match.acosh(x) =', math.acosh(x))
print('match.asinh(x) =', math.asinh(x))
