--
-- File generated with SQLiteStudio v3.4.21 on Thu Mar 5 19:34:19 2026
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: ATTENDEE
DROP TABLE IF EXISTS ATTENDEE;
CREATE TABLE IF NOT EXISTS ATTENDEE (
    ATTENDED_ID INTEGER      PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME  VARCHAR (30) NOT NULL,
    LAST_NAME   VARCHAR (30) NOT NULL,
    PHONE       INTEGER,
    EMAL        VARCHAR (30),
    VIP         BOOLEAN      DEFAULT (0) 
);

-- Table: COMPANY
DROP TABLE IF EXISTS COMPANY;
CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_ID                  INTEGER      PRIMARY KEY AUTOINCREMENT,
    NAME                        VARCHAR (30) NOT NULL,
    DESCRIPTION                 VARCHAR (60),
    PRIMARY_CONTACT_ATTENDEE_ID INTEGER      NOT NULL,
    FOREIGN KEY (
        PRIMARY_CONTACT_ATTENDEE_ID
    )
    REFERENCES ATTENDEE (ATTENDEE_ID) 
);

-- Table: PRESENTATION
DROP TABLE IF EXISTS PRESENTATION;
CREATE TABLE IF NOT EXISTS PRESENTATION (
    PRESENTATION_ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOKED_COMPANY_ID INTEGER NOT NULL,
    BOOKED_ROOM_ID    INTEGER NOT NULL,
    START_TIME        TIME,
    END_TIME          TIME,
    FOREIGN KEY (
        BOOKED_COMPANY_ID
    )
    REFERENCES COMPANY (COMPANY_ID),
    FOREIGN KEY (
        BOOKED_ROOM_ID
    )
    REFERENCES ROOM (ROOM_ID) 
);

-- Table: PRESENTATION_ATTENDANCE
DROP TABLE IF EXISTS PRESENTATION_ATTENDANCE;
CREATE TABLE IF NOT EXISTS PRESENTATION_ATTENDANCE (
    TICKET_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    PRESENTATION_ID INTEGER,
    ATTENDEE_ID     INTEGER,
    FOREIGN KEY (
        PRESENTATION_ID
    )
    REFERENCES PRESENTATION (PRESENTATION_ID),
    FOREIGN KEY (
        ATTENDEE_ID
    )
    REFERENCES ATTENDEE (ATTENDEE) 
);

-- Table: ROOM
DROP TABLE IF EXISTS ROOM;
CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FLOOR_NUMBER INTEGER NOT NULL,
    SEAT_CAPACITY INTEGER NOT NULL
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
