'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq
Imports System.Data.Common
Imports System.Data.Entity


Partial Public Class NorthwindEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NorthwindEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property Products() As DbSet(Of Product)

    Public Overridable Function CustOrdersOrders(customerID As String) As ObjectResult(Of CustOrdersOrders_Result)
        Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrdersOrders_Result)("CustOrdersOrders", customerIDParameter)
    End Function

End Class
