//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOne
    {
        public string Col1 { get; set; }
        public int Col2 { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoCol { get; set; }
        public System.Guid UIDCOL { get; set; }
        public string SPACOL { get; set; }
    }
}
